---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1l6xvasqcxc45h2enksffn5t36mn7994w382v64krkk054zup0aaq4jy33c
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1l6xvasqcxc45h2enksffn5t36mn7994w382v64krkk054zup0aaq4jy33c
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1l6xvasqcxc45h2enksffn5t36mn7994w382v64krkk054zup0aaq4jy33c
  - path_regex: .*\.sops\.ya?ml
    key_groups:
      - age:
          age1l6xvasqcxc45h2enksffn5t36mn7994w382v64krkk054zup0aaq4jy33c
