---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-keycloak
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-iscsi-ssd
    - name: cluster-apps-renait-ldap
  path: ./kubernetes/apps/security/keycloak/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
