kind: ENC[AES256_GCM,data:FTQniqrf,iv:s2weXhRWirnXz8ie3V2WHQGQt0C/wSUTgEIbdXmcv0E=,tag:5dATpY1Wczu2udk2TjGugQ==,type:str]
ansible_user: ENC[AES256_GCM,data:MVnOm8C5,iv:Cj8RLUUVhmhhLsuvKRyN3+11Voa7s23p/6fetyTWKdw=,tag:72OsKRnm6Ru076cm17v7zQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:3aIoUZzbQ4c=,iv:s/9pV/s0d85XpxWQpD61kr1kP5UyoYlW74xYvUXt84I=,tag:cXEDOWvtqQqRv+hzRIkDJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l6xvasqcxc45h2enksffn5t36mn7994w382v64krkk054zup0aaq4jy33c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVTB6STdhU0Q5QTA2czhk
            SEJudUg2cXhxcE9RQXhGcnNxc0kyZkNpMEg4Ci9zcVpmdS96aFZvak9MVlRaSGQ5
            NDgzay82Ylh1ZGRiRllUMWsrY0p4aWsKLS0tIHVwdmwyZE5ZTkMvdERmYVBsRVNn
            dnBSS2w0ZGhpT2lZRzd3M0k0cUVQdEkKgMspJgynheLYoJSxKDgzHbls0L280Plk
            MUa/FZUwiM3v+M49oqDxF+zft8TtnwtB1Lc+lUsQyrgrjFEhSgofSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-06T23:27:00Z"
    mac: ENC[AES256_GCM,data:2rY9/5ISEy6spRf19nfQrtPen5icIQMW72VSbKnlKsOlAimKXAeisdfcyO91VW+qh4RjfaUlj2OD/n2ak/NxjIy5KyjsJ60aU1hoWaev05aanlgzCYx2zuT0WujybQDKXQHjJvo3AHdwyrKI8aqCLUNAToh6SKVrRlBPm/j9hkk=,iv:4k8VoeVVv/Iu2mrGj8zmcos8jbC6xCki18n/qH4jvRY=,tag:brdywNVYSgtIPADzU+gMVQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
