kind: ENC[AES256_GCM,data:ZGNHG+K+,iv:KS6VW/Of1bUjndoSU+AI6vbVJu/34Odh9oQjO/YW9P8=,tag:BIO4zmdHxVNnND7gSVe/9g==,type:str]
ansible_user: ENC[AES256_GCM,data:rIAyk6/c,iv:f+NRnqO3Hu+j0EajzK/3tbvaDtLEImLBAtqjDIQZPFI=,tag:Q9JSXluDACscayfAK/3TLw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:h8+Noe9sPOY=,iv:FTrHvl3EU2Ws8opxtjMFyLclqdtD38tkJjJL8RcG588=,tag:CKMCRf9EOWIOSJAz6N1JlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l6xvasqcxc45h2enksffn5t36mn7994w382v64krkk054zup0aaq4jy33c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YmlMbG9Jc3V1dzJKNDM5
            SEd3TDcybEg0eW12UVY1V2dXbXc4bU1yOWdRCllobnUyNEE3ZWR6MzlPSFJLNjB2
            ZlhkZldYM2EwUE9wdElFc293UGI5ZGMKLS0tIDAwZjJOWVF0RFY2SWhnWXlGMG1q
            Yzh1dEdqNHYzQ2N2emNtaFVLQU1sL3cKZzWwEEEVffT7pVuWWB36YSsx9jCFxa5H
            wocnCbOi/ShVnRxHb5iuEvdkhFlls3OIa0bdbalAqHnv22sVSboSwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T17:58:12Z"
    mac: ENC[AES256_GCM,data:tgyEEcjtvzLxRB7kj9tmtpJHOFTEVOHZRo3NlrQ3mCfhkllKPd291flafiM7o0MIdULzoX8sx2VsSqJnNkDnFOMIgmcZV35FRF3XWbe2s06O7bgykqnVWYy5jrKLiMuLUYldrgS8RhaSBTMPy13tztjJeRAEF0MsZcaTmVZcxhI=,iv:t5ixawpAOnq/Xccox7PY/2enT0lHB8X1FYTB+RP+u6Y=,tag:qjp99VgnEDbyfz+gLpylaw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
