kind: ENC[AES256_GCM,data:WrZgF7md,iv:zXrfS7ehtTezwDmGNImXd4qa68ufdVbfOz5LYMMiR1I=,tag:AlaUqbd1GuOicacQZRDEbw==,type:str]
ansible_user: ENC[AES256_GCM,data:Buk3Wv3W,iv:z7egFDxbmHtIKLzwJ8HXz+2xBA39OgteVKbgmhfSpvU=,tag:BGJqn9lW6LJQ1yNAbSj8vQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:xnmP5MIMAGc=,iv:YI887e5I4mIpuTPs3RzImtt7HJIfmgTU1mlU19KwgG8=,tag:xWaEOUETpvMdEof++trzZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l6xvasqcxc45h2enksffn5t36mn7994w382v64krkk054zup0aaq4jy33c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtN21hZFlERjhwdy8vUDgw
            YU8vbFJkRnFhdjFmdndhSmhtZE5wTnFDQkR3Cm1WN1pOL2tqYnNWZ1d6OTNYODdn
            aGJTRkZHQnBMTGQ1Sy9oTERrK1Q0TVEKLS0tIG5tTnR2QzRNTDlHaUZ5QmYyVFh0
            YU9SSUF5R0wxV1Y4a0Ztakg3bDJyR2cKFIOrc5fxoj3Lo3cp2nJ6AtvARUVJ7p20
            CFYaNT0pUQ9bX1RhG+iKytcc1iFUO0v+y6iu6frMmKvQHmH4f/Ygag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T17:58:12Z"
    mac: ENC[AES256_GCM,data:GlUUkAwlIWR0G4x2+T9iYY9Cv2hVm7CzMIEuWEuyjmMGzBeBf3oFv0VScgI6dvRWGBcDzyR7lqD6eoZTqg+XPIv/6y3KQ/FOcUyVjkHQ3zpuNBXSNX76AkmSAF2HmMXgEGQdL7Az4SnkRHlZfpuJBrWvzYeI1bYuvPH8QQoRowk=,iv:X8URNMyAPlTqAR8YxjMxGQOSauYXsxKi3Z9iZh0plAE=,tag:UBKdckVaSbtV/+k8JDg08g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
