kind: ENC[AES256_GCM,data:HfuyUpvi,iv:msjeAb4W2gR9s8uPZBA4/tjXVswqkwDnDZ6b/MxFK4c=,tag:frgAIxhr3d9deXDLoK/AMw==,type:str]
ansible_user: ENC[AES256_GCM,data:p0cwIugT,iv:IRFpQkCn9AOnhF5DUx5CdDjQJ6iokgZKTQIGi88WIzg=,tag:Ir80fCvuDty4Muxyk1PiSw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:p8lLy5f3EYk=,iv:LJKtfDrJWmjuSgzMWv+6G0WJ2H+nl6LjVB4HaJ8SQVU=,tag:XSTzsPtTrzKLnTacNU0YWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l6xvasqcxc45h2enksffn5t36mn7994w382v64krkk054zup0aaq4jy33c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbmZqbDBFbWgyV0t1cUFI
            ZEtJdEtKMXUyR3Vrc0Q0a2g0SzU2YVZqZ1JrCkJSR3hoalVCcDlLbDRyTFFuZWhT
            cVVqWTFhRGEvbHJQYWVleWN2eXdGRUEKLS0tIEVJbGUrOE1SeWhXTTF2YlBqVzZr
            RnZlZEI4akNwaU1mWGNzY3dic1JEY1EKsn/raRC7HQF11rc4K8p/CVYPJOncqx/0
            JWVyzELVPFsoY/va4I0737B1I05tQF+i6/Ct84ZrqinyYuQJZcD/xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-07T00:37:49Z"
    mac: ENC[AES256_GCM,data:3oMZC8k5fiPBljCPquZEWGqRGC+1hjd5h5CWqAmdGhxa49u+57O+8dDO2MKtISjEICmGmQLfdYhLyT+FA4rutCV2CkWh3Ug0WK2fI1JRW9DvgbhYeYeA0bjEHJVVbD4tklYSWvLmzZdmPEEroda3LWljgy2Zl/nTWE9r9LTRZd0=,iv:+qnME1inM8ZKAGpDOFWuWiY2dRX9/oMUOqLxKmAMK2c=,tag:HMYbFpPr3R5l/h2Re0nvPg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
