---
kubernetes:
  children:
    master:
      hosts:
        tf-k8s-master-0:
          ansible_host: 192.168.2.80
    worker:
      hosts:
        tf-k8s-worker-1:
          ansible_host: 192.168.2.81
        tf-k8s-worker-2:
          ansible_host: 192.168.2.82
        tf-k8s-worker-3:
          ansible_host: 192.168.2.83
