---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./kubernetes-dashboard/ks.yaml
  # - ./vpa/ks.yaml
  # - ./goldilocks/ks.yaml
  # Standard resources
  # - ./external-services
