apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:7cZaugcEeWCu/uPWNOmwz+n3kB9WQBezunxwb+j9dSNyGE2oJQ==,iv:IbKWQexnXbObS+JnGF9zwyqn4YGB80s4w7yyJNZg3gU=,tag:nJDvPF4dsQE9eEUpdVFbaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l6xvasqcxc45h2enksffn5t36mn7994w382v64krkk054zup0aaq4jy33c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUjk2RHRlT0gwRzVmSmhj
            ZktoeXBjZ05sdUpYZWZ3eFd1TWg4ZXRySWwwCnJiYVpGaXRtM0lQZ0o2TjZ2RmF1
            ZEdoWTN5eVFtVjBBcy9tbklRaXc4elkKLS0tIFBaeGRTckwxNVdoRHREY2FFRjY2
            c0FMOHVBYmlnNVg5MjRmcFdUcGJBR0EK4vpMB4Ial7C2JJpQHhtu1BPCvsbJR8Mt
            Nc18qJWLNF4suB1M7j0xCN9MQXj7r5SInSemUv84o75jpFYc+o3HSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T17:58:12Z"
    mac: ENC[AES256_GCM,data:wZPC/pKMsBXq1OGpQV+xtvyPnPwrOFh0CehF873NTc+MUuqcA4TbcRTwzy0r6LOyxtTE5Ise33eYB0kYUwHPyc1WU91awSXOV1T8ChjRw8bCOuqG6qeYwSOx359t21TIf1voJ/nu0+o5FbZnbj9K2Ir+oks0NKKZ46lVeC+UBSo=,iv:Hnpcu7A95RFS0Jx9XkPDw9v7CuqqjsC2lX7vrkNaaUo=,tag:EAQ8j7ofgvpZxNd654G2DA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
