apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:dg1WSB63wxfpFurUl6xk57k=,iv:KYkxj/zw2w7VzAS9zBRBOeRGYZxx05ZVNY3Hg+G1s+8=,tag:VJ0wBpxvhRjVY8Dz2tXXiQ==,type:str]
    api-key: ENC[AES256_GCM,data:gb1NBGpdxcfxmfg5sMEFAOqPJzqFaycKnMrQ4zqBM1tyv0bt7Q==,iv:TQVC8JypgrwrdDtHcLektpI8Vdr1a+ClkfFnuWWN0yk=,tag:8LJisTSWIY4MN96iasL9JA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l6xvasqcxc45h2enksffn5t36mn7994w382v64krkk054zup0aaq4jy33c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNGNUSURXT0dhSjArWkxF
            ZDBDc2hDRHNjcFRBQ3NVYlJNcmtIaVpyVHl3CjE0cC9kb2FReXNuTklGOWNrUnpX
            UHB5djZrMGpUK1dpbHI3N2FMR2N0NkkKLS0tIExiOSt3Yjg3UzhIVzd5R1YxMHpM
            em9JdUFFd2Y0MU9yNkJmc21TREZkNmsK9MHMIrMRSZStrfl2eVhe7Fx8cI3dB9Vp
            okPV2w7j9LZHcDeilELRFA9hTMl6YJQJrWTQm+VXsTvpW0dymVATqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T17:58:12Z"
    mac: ENC[AES256_GCM,data:Jvon2+UCNO7GPJlW/qAdQLFojk1fF5uS+kTKZfapq1XgIiO827ZH5nkT4z2c4Y0ktEsN875ZRWJshOGdUuAQaZfdSma8ZyYuFnwU+R68Nf+0jiVQGEk9WhgyFxWezzGxFq/FtDMav8V0mlQzvkFHJn0/zsMIOLckRsB34uNyNjk=,iv:t8snKtUMBX9ymxBs0HmeUxWFOFYqHsWCneE26M6IDnQ=,tag:E1w4969QsUEBxjHQmdU0gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
