---
# (string) Timezone for the servers
timezone: "Europe/Amsterdam"

# (list) Additional ssh public keys to add to the nodes
public_ssh_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEpfiZzxO1X6kObMrLanMSX6nKo5ozCho39vX4PuA3/j eopg@roelof-B550-AORUS"

fedora:
  packages:
    - dnf-plugin-system-upgrade
    - dnf-utils
    - hdparm
    - htop
    - ipvsadm
    - lm_sensors
    - nano
    - nvme-cli
    - socat
    - python3-kubernetes
    - python3-libselinux
    - python3-pyyaml

ubuntu:
  packages:
    - hdparm
    - htop
    - ipvsadm
    - lm-sensors
    - nano
    - nfs-common
    - nvme-cli
    - socat
    - python3-kubernetes
    - python3-yaml
