---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "renait-production"
  namespace: networking
spec:
  secretName: "renait-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "renait.nl"
  dnsNames:
    - "renait.nl"
    - "*.renait.nl"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "renait-staging"
  namespace: networking
spec:
  secretName: "renait-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "renait.nl"
  dnsNames:
    - "renait.nl"
    - "*.renait.nl"
