apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:i6/IQu89Y8f9wfbzpsn5qhvpa7HyFya2uzB6fXJJJW8In9FMadaZHreqFoKTDgOlE3BHC/UYzOe2LDvu,iv:Dw8Vm4tukRz3lxBRtg3s2I9JP9Xx6IUa2kYVmiqmZxk=,tag:X0vS9yk+eJ/OX0bGC+fdug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l6xvasqcxc45h2enksffn5t36mn7994w382v64krkk054zup0aaq4jy33c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRXVhNFByQWN1WFdsU09X
            WmpJNzhmZTBldE9ocG1uSGQwMFFHdm01aFJZCkR1Q3dxMHJHcGhhbnh0c3BjNFFo
            aGVhSnFZdmpEMXNCcDJMTTlDNEhmREUKLS0tIFBPamlmUE1CZ2g1Y1ZIZ2RGUVVy
            S3ZQOXcrQkdUU1Npc3o4eDNNUUNJQzQKu6AVuedtjrW0mmFojRJduENcQDhoKwXh
            t+XayoZ8XK6StGqm7OzHc0aOQrfnvDUOgJFpQOuGVIAuLFf78pDeIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T17:58:12Z"
    mac: ENC[AES256_GCM,data:FvJJNxS5YFCrfDZGrFpm4FqafMTlfDFKJsSo4PSLkQl3P/0/hSan3z9O4JnNj41Xx9G+Z2YRxnjm4dXG3dW8XewWC6J6xalaAz2HDFPuLwRXPvSj7guCcr2AAyWVD5kymda9Y2oJQa/2aEbGmd0a5l5dumH4RHsvSXCWiApytos=,iv:ldHIKvBviHlB92dcje4ENxv7mUSRza/Jko29Q8UDmQ4=,tag:Vh+HPCMJmej/1O51I/5aQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
