---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Amsterdam"
  NET_NODE_CIDR: "192.168.14.0/24"
  NET_POD_CIDR: "10.244.0.0/16"
  NET_SVC_CIDR: "10.96.0.0/12"
  NET_EIP_CIDR: "192.168.19.0/24"
  SVC_NGINX_ADDR: "192.168.19.101"
