apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:A/TS+RzKYr/u,iv:Ef0y6cuem9EUp4MMmLXbartdmOqYvJCAAGXRwTrzVac=,tag:bwK9nAd5YowTm+q+FlLyaw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:YhOxupaZrsYNBV3ZU00Dc7U=,iv:MOLTxKRkuy4hnKGzTjAu/0hsYoJLVsv9y1i/wiWq/xs=,tag:PKk/SdzLtNI3nXXLgMvo8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l6xvasqcxc45h2enksffn5t36mn7994w382v64krkk054zup0aaq4jy33c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbUwxZnB1bzFWL2NRaC9h
            ZEgwVmVaWEZKcFRteDRQaGVWNVgxQWtNUUJZCkYrOUhMOHZ1WWMxOEdoSzc3KzJz
            TmVqbmpla2VwcWpha2R5VG1RYm1xcTQKLS0tIFNQenduZWw5a1dEQ0V6MWc1RUxk
            SGtMTGpHU0Z6UjRaZXJNZkNveUdIT1kKng/EPL/XfjKUBTdTNyB0vVPNR8VV+HSS
            2gvoJDcU/jjce0KU8nwRP0MnIQhrWKiw5RrTsoPcHcIG8wjqvPNh6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T17:58:12Z"
    mac: ENC[AES256_GCM,data:A9EI3F3nXLiVY9gCymzqNAvkO7/Rl7VF76UEvbNY1f8x4B0iqxGl3uVUaieDKHXRKrEtwbFhgfJrnnGXqmkUyMztolxKOWoxPjCYVsXJhoJMgzBUGIFLEC9evN2scu3f9GJuV91mHbFqz6zLcxo2s/0U4aBlgxUxKLAWH57Gkro=,iv:/34Cx2aDgYAIVGXuExHUNTpLnr69NpkBA0AydCFI4m8=,tag:yF1yjuUl70u08eSeYe4hDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
