apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:FicvEm/AmPQU,iv:Vr5E8v74esktDvGRquDxpw+9w0L+WxMRBquSSkf3hJY=,tag:O7W3X9KnpHAxx+GHE4LnkQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:pXXNvtUbKeKqEvfTkPqvtmw=,iv:pUYA5Whd771TEtYbhFdJ+Bn2y1Tc5GHV/DvMqvKrjk4=,tag:dwcwpvYD9NJ87idLi84OcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l6xvasqcxc45h2enksffn5t36mn7994w382v64krkk054zup0aaq4jy33c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YjJlTkxOL0tJTElkY1JG
            RzdML3loblh2S1NkYXNIUDNUa2RXeExiZGlnCmhxbHhBSmNWRitBdWRXdXM2dlRX
            aGRBdzFZQk05NGJQbDNrcWRCSmZScUkKLS0tIEZrRzYwejVsYnBoMFBLaU5kcng2
            OHlkK2kzUlNLd0JlOFZqS2E5cTk3NkkKn8p6Mqhuy4VeMFwf0Y3Uh371E5FXiB19
            lNREX/E1dzPFi6jOg799nRR1ezZmKX09R2jEQe7hDzk7U77FVUlPqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-20T14:05:23Z"
    mac: ENC[AES256_GCM,data:iXuk+KXPCCBc3/Jy9txBLo+IfAmFccMOzEi/d3eyRkw9hreiqDXk5t6ur8Gz5QbovXwP22gn31dr6YA7HTz7fbBtyDQk1tBHfLl730vmbDhFhJgg0gfo1qHcQxpxzTGF6qBv82Vb4oZZvYadPTDbsdE7gfZt2SbSyIRsFPXBxu0=,iv:G0r84rRpA9dfFK2+SvdTrM6nxrF9IimugFs7D4CX8Qg=,tag:9+6hLZSgR0KLgiQvTEJWwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
