apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:I+9BCEwRiij/,iv:uzpjdZevTu5M6cbxH/U1FzbftErP67q53iwDZRVkK2I=,tag:v8QIkkR+7rENH41n5jDl/w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:fsW+U/UjA83Y4b58XnlKKVY=,iv:UDQDPvmTfBXUGLGO/GX3EtpEcqmQA8bvA40xTEGrxg8=,tag:7wA5nHFhcdJmMKiYAWBZQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l6xvasqcxc45h2enksffn5t36mn7994w382v64krkk054zup0aaq4jy33c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZ21rVUtSeXVycEJqd0Zk
            ZVN3S09uSWZ6ZURpdm1Vek5xeVlKQUNmY1hFCktlVlROQXd5S1cyMUZ2WVVOMXdj
            ck1KR2J1UWNFUUIyWW5kMGZ5ZHNiV3MKLS0tIC81cW1xOGlhVm1YUGllVEx0OE1E
            SjdJNjd1UWdyWGtsSzNRSGhjbEEvMU0K97K9KCifFfQcxDkI+9RYCz7ZVmphbpLy
            aQW6u2177ea1JK8lOwgZf5TXfnBFzBN/wTgMesVmWVZ6VWML9rQu7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-06T23:42:01Z"
    mac: ENC[AES256_GCM,data:DBxgzfDUTviJycusBsvW3mkKPV3lpS8KWkvD4yefvrXTW3Kuui/G5ti5D8Y1jez9Xr0MTB5dVzPvEholIbE+VD4gGgyaFPBfQ4F4E2uonL3gi6huMfRz2R1vJoXzROfnAb2t39nR29eYK/TAZo+Q4vPLpisymIxsv6qUzRRmIeg=,iv:xJTQfnyAm20bTMTMbEal5gFXYYYBGSxE5+ogr3fUDOY=,tag:qzFoNaRiDN/geZ8K2jVbeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
