---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent
  namespace: system-upgrade
spec:
  # renovate: datasource=github-releases depName=k3s-io/k3s
  version: v1.26.2+k3s1
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  prepare:
    image: rancher/k3s-upgrade
    args: ["prepare", "server"]
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
