---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server
  namespace: system-upgrade
spec:
  # renovate: datasource=github-releases depName=k3s-io/k3s
  version: "v1.26.2+k3s1"
  serviceAccountName: system-upgrade
  concurrency: 1 # Batch size (roughly maps to maximum number of unschedulable nodes)
  nodeSelector:
    matchExpressions:
      - {key: k3s-upgrade, operator: Exists}
      - {key: k3s-upgrade, operator: NotIn, values: ["disabled", "false"]}
      - {key: k3os.io/mode, operator: DoesNotExist}
      - {key: node-role.kubernetes.io/control-plane, operator: Exists}
  cordon: true
  upgrade:
    image: rancher/k3s-upgrade
